### ISSUE TITLE
Queue server not working 

### ISSUE THREAD

**Issue by mja00** [EmotionalLove/MatsuQueueBungee#2]
I'm testing out this queue plugin and it's not working properly. I have the config set to the default other than the destination server which is my towny server. The bungee config prioritizes the queue server over the towny server but when I connect to the proxy I get a message saying "Kicked whilst connecting to towny: Server is full!" It's not even putting me into the queue server, and even the one time it did all it said in chat was that the towny server was full and then never put me in queue. Both the queue server and the bungee proxy have on the queue plugin installed(respect bungee and bukkit version). I'm very confused. I've edited the configs a few times to try and figure out why it won't work.

Image of both clients: https://i.imgur.com/YTlPDCJ.png

**Comment by EmotionalLove** [comment]
You closed the issue so maybe you’ve solved it, but make sure the player cap in the server.properties file for both servers is sufficient, for the queue server you typically want to set the player limit for something incredibly high, and for the main server, it should be the total amount of slots combined. (So if you have 20 priority and 20 standard, that would be 40)
