### ISSUE TITLE
Attempts to connect to server too quick

### ISSUE THREAD

**Issue by lunaboppin** [EmotionalLove/MatsuQueueBungee#9]
When a player leaves the server and a slot if free in the server, the queue system attempts to join too quick and gives 'Server is full!' error

https://i.imgur.com/uDjMIo2.png

**Comment by EmotionalLove** [comment]
Your player slot limit in your server.properties should be whatever it currently is plus one.

MatsuQueue will enforce the cap in MatsuQueue’s config regardless of how high the server cap is.
